
name: js Lint
#use ESLint

on:
  push:
    branches: [main, dev*]
  pull_request:
    branches: [main, dev*]
    
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
